version: "3.1"
volumes:
  mongostorage:
services:
  mongodb:
    container_name: mongodb
    image: alexpunct/mongo:3.4
    volumes: 
      - mongostorage:/data/db
    ports:
      - 0.0.0.0:27017:27017/tcp
    environment:
      MONGODB_ADMIN_USER: admin
      MONGODB_ADMIN_PASS: admin
      MONGODB_APPLICATION_DATABASE: profilizer
      MONGODB_APPLICATION_USER: admin
      MONGODB_APPLICATION_PASS: admin
  profilizer:
    container_name: profilizer
    image: profilizer
    ports:
      - 0.0.0.0:8080:8080/tcp
    depends_on:
      - mongodb
    environment:
      - DATABASE_HOST=mongodb
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin 
      - DATABASE_NAME=profilizer
      - DATABASE_PORT=27017

  
     