spring:
  data:
    mongodb:
     host: localhost
     port: 27017
     database: profilizer
     username: admin
     password: admin
server:
  contextPath: /profilizer/api

web:
  security:
    username: user
    password: user123
    role: USER
---
spring:
    profiles: container
    data:
      mongodb:
         host: ${DATABASE_HOST}
         port: ${DATABASE_PORT}
         database: ${DATABASE_NAME}
         username: ${DATABASE_USER}
         password: ${DATABASE_PASSWORD}
server:
       contextPath: /profilizer/api